ML Model

In [201]:
import pandas as pd
import numpy as np

In [202]:
data_prepro = pd.read_csv(r'C:\Users\Pratham\Downloads\Absenteeism_preprocessed.csv')
# data_prepro

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0                 30          0         2    1                          4  
1                 31          0         1    0                          0  
2                 31          0         0    0                          2  
3                 24          0         2    0                          4  
4                 30          0         2    1                          2  
..               ...        ...       ...  ...                        ...  
695               22          1         2    0                          8  
696               24          0         1    2                          3  
697               25          1         0    0                          8  
698               25          1         0    0                          2  
699               25          0         1    1                          2  

[700 rows x 15 columns]

# creating targets.

In [203]:
data_prepro['Absenteeism Time in Hours'].median()

3.0

In [204]:
targets = np.where(data_prepro['Absenteeism Time in Hours']>3,1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [205]:
data_prepro['excess abs'] = targets
data_prepro.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   excess abs  
0           1  
1           0  
2           0  
3           1  
4           0

In [206]:
targets.sum()/ targets.shape[0]

0.45571428571428574

In [219]:
data_withtarg = data_prepro.drop(['Absenteeism Time in Hours'],axis = 1)

In [220]:
data_withtarg.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  excess abs  
0               30          0         2    1           1  
1               31          0         1    0           0  
2               31          0         0    0           0  
3               24          0         2    0           1  
4               30          0         2    1           0

# select input for reg.

In [221]:
data_withtarg.shape

(700, 15)

In [222]:
data_withtarg.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

In [223]:
unscalled_ip = data_withtarg.iloc[:,:-1]

# stanardize data

In [224]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [225]:
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

class CustomScaler(BaseEstimator,TransformerMixin): 
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.columns = columns
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std

    def fit(self, X, y=None):
        self.scaler = StandardScaler(copy=self.copy, with_mean=self.with_mean, with_std=self.with_std)
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self 
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [226]:
unscalled_ip.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [215]:
# columns_to_scale = ['Month Value',
#        'Day of the Week', 'Transportation Expense', 'Distance to Work',
#        'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
#        'Children', 'Pet']
colums_to_omit = ['Reason1', 'Reason_2', 'Reason_3', 'Reason_4' , 'Education']

In [227]:
colums_to_omit = [x for x  in unscalled_ip.columns.values if x not in colums_to_omit]

In [228]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [229]:
absenteeism_scaler.fit(unscalled_ip)

CustomScaler(columns=['Month Value', 'Day of the Week',
                      'Transportation Expense', 'Distance to Work', 'Age',
                      'Daily Work Load Average', 'Body Mass Index', 'Education',
                      'Children', 'Pet'])

In [230]:
scaled_inputs = absenteeism_scaler.transform(unscalled_ip)

In [231]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1     0.030796        -0.800950   
1           0         0         0         0     0.030796        -0.800950   
2           0         0         0         1     0.030796        -0.232900   
3           1         0         0         0     0.030796         0.335149   
4           0         0         0         1     0.030796         0.335149   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0    -0.568019        -0.232900   
696         1         0         0         0    -0.568019        -0.232900   
697         1         0         0         0    -0.568019         0.335149   
698         0         0         0         1    -0.568019         0.335149   
699         0         0         0         1    -0.568019         0.335149   

     Transportation Expense  Distance to Work       Age  \
0                  1.005844          0.412816 -0.536062   
1                 -1.574681         -1.141882  2.130803   
2                 -0.654143          1.426749  0.248310   
3                  0.854936         -1.682647  0.405184   
4                  1.005844          0.412816 -0.536062   
..                      ...               ...       ...   
695               -0.654143         -0.533522  0.562059   
696                0.040034         -0.263140 -1.320435   
697                1.624567         -0.939096 -1.320435   
698                0.190942         -0.939096 -0.692937   
699                1.036026          0.074838  0.562059   

     Daily Work Load Average  Body Mass Index  Education  Children       Pet  
0                  -0.806331         0.767431  -0.447980  0.880469  0.268487  
1                  -0.806331         1.002633  -0.447980 -0.019280 -0.589690  
2                  -0.806331         1.002633  -0.447980 -0.919030 -0.589690  
3                  -0.806331        -0.643782  -0.447980  0.880469 -0.589690  
4                  -0.806331         0.767431  -0.447980  0.880469  0.268487  
..                       ...              ...        ...       ...       ...  
695                -0.853789        -1.114186   2.232242  0.880469 -0.589690  
696                -0.853789        -0.643782  -0.447980 -0.019280  1.126663  
697                -0.853789        -0.408580   2.232242 -0.919030 -0.589690  
698                -0.853789        -0.408580   2.232242 -0.919030 -0.589690  
699                -0.853789        -0.408580  -0.447980 -0.019280  0.268487  

[700 rows x 14 columns]

In [232]:
scaled_inputs.shape

(700, 14)

# split into train & test and shuffle

# split


In [233]:
from sklearn.model_selection import train_test_split


In [234]:
train_test_split(scaled_inputs,targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 171         0         0         0         1    -1.166834         0.903199   
 29          0         0         0         1     0.330204         0.903199   
 381         0         0         0         1    -1.466241        -1.368999   
 443         0         0         0         1    -0.268611        -0.800950   
 338         0         0         0         1     1.228426         0.335149   
 ..        ...       ...       ...       ...          ...              ...   
 567         0         0         0         1     1.527833         0.335149   
 342         0         0         0         1    -0.568019         0.335149   
 209         1         0         0         0     1.228426         1.471248   
 90          0         0         0         1     1.228426        -0.232900   
 376         0         0         0         1    -1.466241        -0.232900   
 
      Transportation Expense  Distance to Work       Age  \
 1

In [235]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs,targets, train_size = 0.8,random_state= 20)

In [236]:
print(x_train.shape,y_train.shape)

(560, 14) (560,)


In [237]:
print(x_test.shape,y_test.shape)

(140, 14) (140,)


# logistic regression 

In [238]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [239]:
reg = LogisticRegression()

In [240]:
reg.fit(x_train,y_train)

LogisticRegression()

In [241]:
reg.score(x_train,y_train)

0.7660714285714286

# check accuracy

In [242]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [243]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [244]:
model_output == y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [245]:
np.sum(model_output == y_train)

429

In [246]:
model_output.shape[0]

560

In [247]:
np.sum(model_output == y_train)/model_output.shape[0]

0.7660714285714286

# finding coefficents

In [248]:
reg.intercept_

array([-1.65467097])

In [249]:
reg.coef_

array([[ 2.78862535,  0.92769133,  3.10680325,  0.81612674,  0.013678  ,
        -0.07597497,  0.62827389, -0.03204259, -0.17407337, -0.02362769,
         0.27897256, -0.10925701,  0.35896925, -0.27524358]])

In [250]:
unscalled_ip.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [251]:
feature_name = unscalled_ip.columns.values

In [252]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  coefficient
0                  Reason_1     2.788625
1                  Reason_2     0.927691
2                  Reason_3     3.106803
3                  Reason_4     0.816127
4               Month Value     0.013678
5           Day of the Week    -0.075975
6    Transportation Expense     0.628274
7          Distance to Work    -0.032043
8                       Age    -0.174073
9   Daily Work Load Average    -0.023628
10          Body Mass Index     0.278973
11                Education    -0.109257
12                 Children     0.358969
13                      Pet    -0.275244

In [253]:
summary_table.index = summary_table.index + 1
summary_table.iloc[0] = ['intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  coefficient
1                 intercept    -1.654671
2                  Reason_2     0.927691
3                  Reason_3     3.106803
4                  Reason_4     0.816127
5               Month Value     0.013678
6           Day of the Week    -0.075975
7    Transportation Expense     0.628274
8          Distance to Work    -0.032043
9                       Age    -0.174073
10  Daily Work Load Average    -0.023628
11          Body Mass Index     0.278973
12                Education    -0.109257
13                 Children     0.358969
14                      Pet    -0.275244

# interpreting the coef

In [254]:
summary_table['odds_ratio'] = np.exp(summary_table.coefficient)
summary_table

Feature name  coefficient  odds_ratio
1                 intercept    -1.654671    0.191155
2                  Reason_2     0.927691    2.528665
3                  Reason_3     3.106803   22.349484
4                  Reason_4     0.816127    2.261723
5               Month Value     0.013678    1.013772
6           Day of the Week    -0.075975    0.926839
7    Transportation Expense     0.628274    1.874372
8          Distance to Work    -0.032043    0.968465
9                       Age    -0.174073    0.840235
10  Daily Work Load Average    -0.023628    0.976649
11          Body Mass Index     0.278973    1.321771
12                Education    -0.109257    0.896500
13                 Children     0.358969    1.431853
14                      Pet    -0.275244    0.759387

In [255]:
summary_table.sort_values('odds_ratio' , ascending = False)

Feature name  coefficient  odds_ratio
3                  Reason_3     3.106803   22.349484
2                  Reason_2     0.927691    2.528665
4                  Reason_4     0.816127    2.261723
7    Transportation Expense     0.628274    1.874372
13                 Children     0.358969    1.431853
11          Body Mass Index     0.278973    1.321771
5               Month Value     0.013678    1.013772
10  Daily Work Load Average    -0.023628    0.976649
8          Distance to Work    -0.032043    0.968465
6           Day of the Week    -0.075975    0.926839
12                Education    -0.109257    0.896500
9                       Age    -0.174073    0.840235
14                      Pet    -0.275244    0.759387
1                 intercept    -1.654671    0.191155

# TEsting

In [256]:
reg.score(x_test,y_test)

0.75

In [257]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.75860887, 0.24139113],
       [0.62409894, 0.37590106],
       [0.45511724, 0.54488276],
       [0.77428775, 0.22571225],
       [0.07513669, 0.92486331],
       [0.28649954, 0.71350046],
       [0.29986092, 0.70013908],
       [0.11162113, 0.88837887],
       [0.75263651, 0.24736349],
       [0.75772395, 0.24227605],
       [0.49745939, 0.50254061],
       [0.18040561, 0.81959439],
       [0.06963821, 0.93036179],
       [0.68255992, 0.31744008],
       [0.27764405, 0.72235595],
       [0.50074571, 0.49925429],
       [0.51572453, 0.48427547],
       [0.55104397, 0.44895603],
       [0.38140894, 0.61859106],
       [0.05651624, 0.94348376],
       [0.73276549, 0.26723451],
       [0.76665612, 0.23334388],
       [0.44195989, 0.55804011],
       [0.45927099, 0.54072901],
       [0.22345683, 0.77654317],
       [0.7529486 , 0.2470514 ],
       [0.4927068 , 0.5072932 ],
       [0.87619335, 0.12380665],
       [0.23568562, 0.76431438],
       [0.75884681, 0.24115319],
       [0.

In [258]:
predicted_proba[:,1]

array([0.24139113, 0.37590106, 0.54488276, 0.22571225, 0.92486331,
       0.71350046, 0.70013908, 0.88837887, 0.24736349, 0.24227605,
       0.50254061, 0.81959439, 0.93036179, 0.31744008, 0.72235595,
       0.49925429, 0.48427547, 0.44895603, 0.61859106, 0.94348376,
       0.26723451, 0.23334388, 0.55804011, 0.54072901, 0.77654317,
       0.2470514 , 0.5072932 , 0.12380665, 0.76431438, 0.24115319,
       0.40043974, 0.7215955 , 0.68183726, 0.50358934, 0.23334388,
       0.57756322, 0.26129038, 0.75900943, 0.45319923, 0.59030059,
       0.25180807, 0.44918422, 0.24313641, 0.39439222, 0.80250172,
       0.63987255, 0.73972906, 0.24944463, 0.2683629 , 0.21503575,
       0.51601174, 0.30383736, 0.68949705, 0.26237082, 0.84148312,
       0.42064057, 0.91526262, 0.29513725, 0.31436467, 0.30968266,
       0.73018836, 0.6646531 , 0.28905842, 0.78786617, 0.24932081,
       0.24357357, 0.07560259, 0.24955567, 0.7673176 , 0.32162264,
       0.25227925, 0.31554182, 0.89486773, 0.44790333, 0.61231